---
title: "II PARCIAL"
author: "JEREMY GARCIA SOLANO C33171"
date: "30-12-2025"
subtitle: "HERRAMIENTAS DE CIENCIA DE DATOS"
institute: "UNIVERSIDAD DE COSTA RICA"
titlepage: TRUE
format:
  html: 
    embed-resources: TRUE
---

## Carga de paquetes

```{r}
library(readr)
library(tidyverse)
library(DescTools)
library(rpart)
library(rpart.plot)
```

## Importar base de datos

```{r}
moras <- read.csv("C:/Users/jereg/Downloads/moras.txt")

moras$SALARIO <- gsub(",", ".", moras$SALARIO) #Cambia las comas por puntos
moras$SALARIO <- as.numeric(moras$SALARIO)
```

## 2.Resumen de 5 números

```{r}
moras %>% 
  select(SALARIO,EDAD) %>% 
  summary()
```

## 3. Nueva columna con Z-SCORE

```{r,eval=FALSE}
llenar_NA <- function(df){
  df[df == ""] <- NA
  return(df)
}
moras<-llenar_NA(moras)
  

moras <- moras %>% 
  mutate(
    Z_EDAD =  abs((EDAD - mean(EDAD,na.rm=TRUE)) / sd(EDAD,na.rm=TRUE)),
    CLASIFICACIÓN_EDAD = ifelse(Z_EDAD>1.96,"ATÍPICO","NORMAL"),
    Z_SALARIO =  abs((SALARIO - mean(SALARIO,na.rm=TRUE)) / sd(SALARIO,na.rm=TRUE)),
    CLASIFICACIÓN_SALARIO = ifelse(Z_SALARIO>1.96,"ATÍPICO","NORMAL")
  )
```

```{r}
head(moras)
```

## 4.Calcular el % de NA por columna

```{r}
colSums(is.na(moras)) / nrow(moras) * 100
```


## 5.Imputar NA´s

```{r}
moras$SALARIO[is.na(moras$SALARIO)] <- median(moras$SALARIO, na.rm = TRUE) #Se imputa la mediana ya que es menos influenciada por los outliers

moras$EDAD[is.na(moras$EDAD)] <- median(moras$EDAD, na.rm = TRUE) #Se imputa la mediana ya que es menos influenciada por los outliers

moras$TIPO_ASEGURAMIENTO[is.na(moras$TIPO_ASEGURAMIENTO)] <- Mode(moras$TIPO_ASEGURAMIENTO,na.rm=TRUE) #Se imputa la moda

```